CREATE DATABASE SchoolDB;

CREATE SCHEMA school;

CREATE TABLE school.KHOA_HOC (
	ma_kh INT PRIMARY KEY,
	ten_kh VARCHAR(150) NOT NULL,
	mo_ta TEXT,
	hoc_phi DECIMAL(12, 2) NOT NULL
);

CREATE TABLE school.GIANG_VIEN (
	ma_gv INT PRIMARY KEY,
	ho_ten VARCHAR(100) NOT NULL,
	chuyen_nganh VARCHAR(100),
	so_dien_thoai VARCHAR(15)
);

CREATE TABLE school.HOC_VIEN (
	ma_hv INT PRIMARY KEY,
	ho_ten VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	ngay_dang_ky DATE DEFAULT CURRENT_DATE
);

CREATE TABLE school.LOP_HOC (
	ma_lop INT PRIMARY KEY,
	thoi_gian_hoc VARCHAR(100),
	ma_gv INT NOT NULL,
	ma_kh INT NOT NULL
);

CREATE TABLE school.DANG_KY (
	ma_hv INT NOT NULL,
	ma_lop INT NOT NULL,
	ngay_dk DATE DEFAULT CURRENT_DATE,
	trang_thai VARCHAR(20) DEFAULT 'cho_xac_nhan',
	PRIMARY KEY (ma_hv, ma_lop)
);

ALTER TABLE school.LOP_HOC
ADD CONSTRAINT FOREIGN_KEY_LOPHOC_GIANGVIEN FOREIGN KEY (ma_gv) REFERENCES school.GIANG_VIEN (ma_gv);

ALTER TABLE school.LOP_HOC
ADD CONSTRAINT FOREIGN_KEY_LOPHOC_KHOAHOC FOREIGN KEY (ma_kh) REFERENCES school.KHOA_HOC (ma_kh);

ALTER TABLE school.DANG_KY
ADD CONSTRAINT FOREIGN_KEY_DANGKY_HOCVIEN FOREIGN KEY (ma_hv) REFERENCES school.HOC_VIEN (ma_hv);

ALTER TABLE school.DANG_KY
ADD CONSTRAINT FOREIGN_KEY_DANGKY_LOPHOC FOREIGN KEY (ma_lop) REFERENCES school.LOP_HOC (ma_lop);